name: bug
description: "A Broke Flutter Demo."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
